"""
OmniPhysiBoSS/wrappers/_utils/verify_xml.py
---
This sub-module handles the strict structural verification of your simulation configurations. The logic is decoupled into four focused validation checks coordinated by a single package-level entrypoint.

"""


import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Dict, Tuple


# ----------------------------------
# Main wrapper 
# ----------------------------------

# Orchestration runtime interface
## Global entrypoint coordination function
def verify_xml_dependencies(xml_path: Path, maboss_models_map: Dict[str, Dict[str, Path]]) -> None:
    """
    Coordinates modular validation checks to ensure project configuration integrity across models and disk targets.

    :param xml_path: Path to the simulation setup XML file.
    :type xml_path: Path
    :param maboss_models_map: Paired model structure dictionary generated by discovery utilities.
    :type maboss_models_map: Dict[str, Dict[str, Path]]
    """
    # Parse document structure layout
    tree = ET.parse(xml_path)
    root = tree.getroot()
    intracellular_found = False

    # Process all structural cell definitions in sequence
    ## Core mapping validation loop
    for cell_def in root.findall(".//cell_definition"):
        cell_name = cell_def.attrib.get("name", "Unknown_Cell")
        intracellular = cell_def.find(".//phenotype/intracellular")
        
        if intracellular is not None and intracellular.attrib.get("type") == "maboss":
            intracellular_found = True
            
            ### Execute atomic validations using helper routines
            bnd_file, cfg_file = _validate_intracellular_elements(cell_name, intracellular)
            model_prefix = _validate_prefix_match(cell_name, bnd_file, cfg_file)
            _validate_map_and_disk_presence(cell_name, model_prefix, bnd_file, cfg_file, maboss_models_map)
            
            print(f" -> Cell '{cell_name}' structural binding verified with MaBoSS model: '{model_prefix}'")

    # Handle empty multi-scale model bounds faults
    if not intracellular_found:
        raise ValueError(f"Validation Error: The configuration file {xml_path} contains no cell definitions with an intracellular MaBoSS engine.")

    # Execute spatial architecture dependencies verification
    _validate_external_spatial_files(root, xml_path)

# ----------------------------------
# Helpers 
# ----------------------------------

# XML structural validation sub-layer
## Atomic validation helper routines
def _validate_intracellular_elements(cell_name: str, intracellular: ET.Element) -> Tuple[str, str]:
    """
    Validates the physical presence of MaBoSS filename tags inside an intracellular node.

    :param cell_name: Name of the cell definition boundary being evaluated.
    :type cell_name: str
    :param intracellular: XML element pointing to the intracellular block.
    :type intracellular: ET.Element
    :raises ValueError: If the required bnd_filename or cfg_filename tags are missing.
    :return: A tuple containing the raw string contents of (bnd_filename, cfg_filename).
    :rtype: Tuple[str, str]
    """
    # Retrieve required structural elements
    ## Locate tag sub-nodes
    bnd_node = intracellular.find("bnd_filename")
    cfg_node = intracellular.find("cfg_filename")
    
    # Verify elements are not null or empty
    ## Check boundary file token existence
    if bnd_node is None or bnd_node.text is None:
        ### Raise error on missing structural architecture components
        raise ValueError(f"Validation Error: Cell '{cell_name}' is missing the <bnd_filename> tag.")
        
    ## Check configuration file token existence
    if cfg_node is None or cfg_node.text is None:
        ### Raise error on missing parameter profile components
        raise ValueError(f"Validation Error: Cell '{cell_name}' is missing the <cfg_filename> tag.")

    return bnd_node.text.strip(), cfg_node.text.strip()


def _validate_prefix_match(cell_name: str, bnd_filename: str, cfg_filename: str) -> str:
    """
    Ensures that the network topology and parameter files share an identical filename stem.

    :param cell_name: Name of the cell definition boundary being evaluated.
    :type cell_name: str
    :param bnd_filename: Filename string extracted from the bnd_filename XML node.
    :type bnd_filename: str
    :param cfg_filename: Filename string extracted from the cfg_filename XML node.
    :type cfg_filename: str
    :raises ValueError: If the file stems do not match.
    :return: The verified common model prefix stem.
    :rtype: str
    """
    # Extract file prefix stems
    ## Convert strings to path stems to strip paths and suffixes
    bnd_prefix = Path(bnd_filename).stem
    cfg_prefix = Path(cfg_filename).stem

    # Cross-verify prefix structural match
    ## Check text identity between tokens
    if bnd_prefix != cfg_prefix:
        ### Abort potok on asynchronous naming conventions
        raise ValueError(
            f"Validation Error in Cell '{cell_name}': "
            f"BND filename '{bnd_filename}' uses a different prefix than CFG filename '{cfg_filename}'."
        )

    return bnd_prefix


def _validate_map_and_disk_presence(
    cell_name: str, 
    prefix: str, 
    bnd_filename: str, 
    cfg_filename: str, 
    maboss_models_map: Dict[str, Dict[str, Path]]
) -> None:
    """
    Verifies that the extracted prefix is registered in the tracking map and exists on disk.

    :param cell_name: Name of the cell definition boundary being evaluated.
    :type cell_name: str
    :param prefix: Verified model naming prefix.
    :type prefix: str
    :param bnd_filename: Expected network topology filename.
    :type bnd_filename: str
    :param cfg_filename: Expected configuration profile filename.
    :type cfg_filename: str
    :param maboss_models_map: Map linking prefixes to paired asset disk paths.
    :type maboss_models_map: Dict[str, Dict[str, Path]]
    :raises ValueError: If the model prefix is completely missing from the tracking map.
    :raises FileNotFoundError: If the verified files are missing from the local storage layer.
    """
    # Verify dictionary map tracking bounds
    ## Check mapping context container keys
    if prefix not in maboss_models_map:
        ### Abort execution on unregistered dependencies
        raise ValueError(
            f"Validation Error: Cell '{cell_name}' references MaBoSS model prefix '{prefix}' "
            f"({bnd_filename}/{cfg_filename}), but this model was not found in your source map."
        )

    # Verify physical file existence on hardware volumes
    ## Extract path maps from context dictionary
    target_paths = maboss_models_map[prefix]
    
    ## Check network architecture file path
    if not target_paths["bnd"].exists():
        ### Raise error on detached symlink or deleted file assets
        raise FileNotFoundError(
            f"Validation Error: Cell '{cell_name}' references '{bnd_filename}', "
            f"but the file does not physically exist at: {target_paths['bnd']}"
        )
        
    ## Check configuration parameters file path
    if not target_paths["cfg"].exists():
        ### Raise error on missing parameters layout file
        raise FileNotFoundError(
            f"Validation Error: Cell '{cell_name}' references '{cfg_filename}', "
            f"but the file does not physically exist at: {target_paths['cfg']}"
        )


def _validate_external_spatial_files(root: ET.Element, xml_path: Path) -> None:
    """
    Validates physical presence of custom spatial layouts and rulesets declared in active XML nodes.

    :param root: Root element of the parsed XML tree layout.
    :type root: ET.Element
    :param xml_path: Direct path to the source user setup XML file.
    :type xml_path: Path
    :raises FileNotFoundError: If an active layout file is missing from the local source directory.
    """
    # Scan structural spatial containers for cell arrangement metrics
    ## Evaluate element conditions paths
    initial_conditions = root.find(".//initial_conditions/cell_positions")
    if initial_conditions is not None and initial_conditions.attrib.get("enabled") == "true":
        file_node = initial_conditions.find("filename")
        if file_node is not None and file_node.text:
            ### Isolate base filename token to check source disk co-location
            base_filename = Path(file_node.text.strip()).name
            resolved_file_path = xml_path.parent / base_filename

            if not resolved_file_path.exists():
                #### Terminate potok on empty initial cell position maps
                raise FileNotFoundError(
                    f"Validation Error: <initial_conditions> requires '{base_filename}', "
                    f"but it does not exist in your source directory: {xml_path.parent}"
                )
            print(f" -> External cell tracking file verified locally: '{base_filename}'")

    # Scan structural rule containers for custom matrix rulesets
    ## Evaluate behavioural rulesets paths
    cell_rules = root.find(".//cell_rules/rulesets")
    if cell_rules is not None:
        for ruleset in cell_rules.findall("ruleset"):
            if ruleset.attrib.get("enabled") == "true":
                file_node = ruleset.find("filename")
                if file_node is not None and file_node.text:
                    #### Isolate filename matching rule formats
                    base_filename = Path(file_node.text.strip()).name
                    resolved_file_path = xml_path.parent / base_filename

                    if not resolved_file_path.exists():
                        ##### Terminate potok on missing cell transition parameters
                        raise FileNotFoundError(
                            f"Validation Error: <ruleset> requires '{base_filename}', "
                            f"but it does not exist in your source directory: {xml_path.parent}"
                        )
                    print(f" -> External cell behavioral ruleset verified locally: '{base_filename}'")


