name: OmniPhysiBoss_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - micromamba
  - pip
  - snakemake>=8.0
  - gxx_linux-64       # Required for potential PhysiCell C++ compilation steps
  - cmake
  - git
  - maboss>=2.5.0      # MaBoSS binary
  - pip:
    - -e .             # Installs the local OmniPhysiBoss package in developer mode